# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 10:43
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwidget',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform.Widget', verbose_name='Widget'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Groups'),
        ),
    ]
