# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:24
from django.db import migrations
import wirecloud.commons.fields


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_remove_userworkspace_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwidget',
            name='positions',
            field=wirecloud.commons.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='iwidget',
            name='variables',
            field=wirecloud.commons.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='market',
            name='options',
            field=wirecloud.commons.fields.JSONField(default={}, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='forcedValues',
            field=wirecloud.commons.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='wiringStatus',
            field=wirecloud.commons.fields.JSONField(blank=True, default={}),
        ),
    ]
