# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 10:49
from django.db import migrations
from wirecloud.platform.migration_utils import multiuser_variables_structure_forwards, multiuser_variables_structure_backwards


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_json_description'),
        ('platform', '0004_auto_20160915_0024'),
    ]

    operations = [
        migrations.RunPython(multiuser_variables_structure_forwards, multiuser_variables_structure_backwards),
    ]
