# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 11:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_remove_iwidget_refused_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformpreference',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='tabpreference',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='workspacepreference',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
    ]
