# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 07:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0007_remove_value_size_constraints_from_preference_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
