# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 07:36
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_migrate_public_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
