# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_make_market_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='searchable',
            field=models.BooleanField(default=True, verbose_name='Searchable'),
        ),
    ]
