# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 10:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0011_workspace_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
