# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0014_workspace_and_tab_title_not_null'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('organization', 'wirecloud_organization'),
                migrations.AlterModelTable('team', 'wirecloud_team'),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='organization',
                    name='group',
                ),
                migrations.RemoveField(
                    model_name='organization',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='team',
                    unique_together=set([]),
                ),
                migrations.RemoveField(
                    model_name='team',
                    name='organization',
                ),
                migrations.RemoveField(
                    model_name='team',
                    name='users',
                ),
                migrations.DeleteModel(
                    name='Organization',
                ),
                migrations.DeleteModel(
                    name='Team',
                ),
            ]
        )
    ]
