# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_squashed_0015_remove_organization_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='requireauth',
            field=models.BooleanField(default=False, verbose_name='Require users to be logged in to access the workspace (This option has only effect if the workspace is public)'),
        ),
    ]
