# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-24 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform', '0016_workspace_requireauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkspace',
            name='accesslevel',
            field=models.SmallIntegerField(choices=[(0, 'Owner'), (1, 'Can Access'), (2, 'Can Edit')], default=1, verbose_name='Access Level'),
        ),
        migrations.RemoveField(
            model_name='userworkspace',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='userworkspace',
            name='reason_ref',
        ),
        migrations.AlterUniqueTogether(
            name='userworkspace',
            unique_together=set([('workspace', 'user')]),
        ),
    ]
