# Generated by Django 2.2.9 on 2020-01-22 19:22

from django.db import migrations
import wirecloud.commons.fields


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0017_remove_workspace_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='iwidget',
            name='permissions',
            field=wirecloud.commons.fields.JSONField(blank=True, default={}),
        ),
    ]
