# Generated by Django 2.2.17 on 2020-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_auto_20200122_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhtml',
            name='cacheable',
            field=models.BooleanField(blank=True, default=True, verbose_name='Cacheable'),
        ),
    ]
