# Generated by Django 2.2.28 on 2024-06-18 12:04

from django.db import migrations

def change_json_format_for_screen_sizes(apps, schema_editor):
    # Changes all iwidget.position fields to use the new JSON format

    IWidget = apps.get_model('platform', 'IWidget')
    for iwidget in IWidget.objects.all():
        if not 'configurations' in iwidget.positions and 'widget' in iwidget.positions:
            iwidget.positions = {
                "configurations": [
                    {
                        "id": 0,
                        "moreOrEqual": 0,
                        "lessOrEqual": -1,
                        "widget": iwidget.positions["widget"]
                    }
                ]
            }
        iwidget.save()

class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0019_auto_20201130_1824'),
    ]

    operations = [
        migrations.RunPython(change_json_format_for_screen_sizes),
    ]
