version: "3"

services:

    wirecloud:
        restart: always
        image: fiware/wirecloud:dev
        ports:
            - 80:8000
        environment:
            - DEBUG=True
        volumes:
            - wirecloud-data:/opt/wirecloud_instance/data
            - wirecloud-static:/var/www/static

volumes:
    wirecloud-data:
    wirecloud-static:
