version: "3"

services:

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - wirecloud-static:/var/www/static:ro
        depends_on:
            - wirecloud


    wirecloud:
        restart: always
        image: fiware/wirecloud:dev
        environment:
            - DEBUG=False
            - FORWARDED_ALLOW_IPS=*
        volumes:
            - wirecloud-data:/opt/wirecloud_instance/data
            - wirecloud-static:/var/www/static

volumes:
    wirecloud-data:
    wirecloud-static:
