<script type="text/javascript" src="{{ STATIC_URL }}js/lib/prototype/prototype.improvements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/ComputedStyle.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/EzWebExt/EzWebExt.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/StyledElements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/interface/NavigationHeader.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/interface/MobileDragboard.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/common/utils.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/common/MobileScrollManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/EzSteroidsAPI/EzSteroidsAPI.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/persistenceEngine/PersistenceEngine.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/catalogue/Catalogue.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/XHtml.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/GadgetTemplate.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/gadgetModel/Gadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/WorkSpace.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/Tab.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariableGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/showcase/showcase.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/contextManager/ContextManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/contextManager/ContextPlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/contextManager/Adaptors.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/dragboard/dragboard.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/wiring_exceptions.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/filter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/connectable.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/wiring.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/jsonFilter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/add-ons/wiring.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/add-ons/connectable.js"></script>
