<script type="text/javascript" src="{{ STATIC_URL }}js/lib/prototype/prototype.improvements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/ComputedStyle.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/EzWebExt/EzWebExt.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/StyledElements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/Expander.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/Accordion.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/LayoutManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/preferencesManager/PreferencesManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/preferencesManager/PlatformPref.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/GadgetTemplate.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/Workspace.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkspaceListItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkspaceItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkspaceView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/TabMenuItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/Tab.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/HistoryManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariableGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/DragboardLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/SmartColumnLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/FreeLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/FullDragboardLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/MarketplaceView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueResource.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueSearchView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueView.js"></script>
