<script type="text/javascript" src="{{ STATIC_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/LayoutManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/preferencesManager/PreferencesManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/preferencesManager/PlatformPref.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/HistoryManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueResource.js"></script>
