<script type="text/javascript" src="{{ STATIC_URL }}js/common/ComputedStyle.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/interface/LayoutManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/common/utils.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/common/MobileScrollManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/HistoryManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/dragboard/dragboard.js"></script>
