<script type="text/javascript" src="{{ STATIC_URL }}js/lib/prototype/prototype.improvements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/ComputedStyle.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/EzWebExt/EzWebExt.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/StyledElements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/interface/NavigationHeader.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/interface/MobileDragboard.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/interface/LayoutManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/common/utils.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/common/MobileScrollManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/io.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/GadgetTemplate.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/Workspace.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/Tab.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/HistoryManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariableGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}iphone/dragboard/dragboard.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/connectable.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wirecloud/Wiring.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wirecloud/Operator.js"></script>
