<script type="text/javascript" src="{{ STATIC_URL }}js/lib/prototype/prototype.improvements.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/common/utils.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/ComputedStyle.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/interfaceLayout/BrowserUtils.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/preferencesManager/PreferencesManager.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/preferencesManager/PlatformPref.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/gadgetModel/GadgetTemplate.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/gadgetModel/Gadget.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/opManager/Workspace.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/opManager/Tab.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/opManager/InitialScriptExecuter.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/varManager/VariableGadget.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/DragboardLayout.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/SmartColumnLayout.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/FreeLayout.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/FullDragboardLayout.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/UserPref.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dragboard/ElementPositions.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/wiring/wiring_exceptions.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/wiring/connectable.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/wiring/connectableInterface.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/catalogue.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/user_commands.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/response_command.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/resource.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/views/list/html_painters.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/views/list/user_command_manager.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/views/list/response_command_dispatcher.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/services.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/catalogue/services_facade.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/interfaceLayout/LayoutManager.js"></script>
