# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 12:24
from django.db import migrations
import wirecloud.commons.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueresource',
            name='json_description',
            field=wirecloud.commons.fields.JSONField(default={}, verbose_name='JSON description'),
        ),
    ]
