<script type="text/javascript" src="{{ STATIC_URL }}js/lib/prototype/prototype.improvements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/constants.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/ComputedStyle.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/io.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/EzWebExt/EzWebExt.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/StyledElements.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/PopupButton.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/Form.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/BrowserUtils.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/BackgroundFadder.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/WindowMenu.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/WirecloudHeader.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/interfaceLayout/LayoutManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/common/modules.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/StyledElements/InputInterfaces.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/preferencesManager/PreferencesManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/preferencesManager/PlatformPref.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/XHtml.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/GadgetTemplate.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/gadgetModel/Gadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/log/LogManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkSpace.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkspaceListItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkspaceItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/WorkspaceView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/TabMenuItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/Tab.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/InitialScriptExecuter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/OpManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/opManager/HistoryManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariableGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/VariablePlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/varManager/varManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/showcase/showcase.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/contextManager/ContextManager.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/contextManager/ContextPlatform.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/DragboardLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/SmartColumnLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/FreeLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/FullDragboardLayout.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/IGadgetMenuItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/PreferencesWindowMenu.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/iGadget.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/dragboard.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/UserPref.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/dragboard/ElementPositions.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/ChannelWindowMenu.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/wiring_exceptions.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/filter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/connectable.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/wiring.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/wiringGUI.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/connectableInterface.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wiring/jsonFilter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wirecloud/ui/MarketplaceViewMenuItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wirecloud/ui/InstanciateMashupWindowMenu.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wirecloud/ui/NewWorkspaceWindowMenu.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/wirecloud/ui/RenameWindowMenu.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/MarketplaceView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/ResourcePainter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareCatalogueView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareCatalogue.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareCatalogueResource.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareCataloguePublishView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareResourceDetailsView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareResourcePainter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareResourceDetailsExtraInfo.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareResourceDetailsPainter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/fiware/FiWareStoreListItems.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueResource.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/ResourceDetailsPainter.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CataloguePublishView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueSearchView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/ResourceDetailsView.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/catalogue/CatalogueView.js"></script>
